/* Generated By:JavaCC: Do not edit this line. SelectorParserConstants.java */
package org.springframework.selector.parser;

public interface SelectorParserConstants {

  int EOF = 0;
  int TK_TRUE = 5;
  int TK_FALSE = 6;
  int TK_NULL = 7;
  int TK_OR = 8;
  int TK_AND = 9;
  int TK_NOT = 10;
  int TK_BETWEEN = 11;
  int TK_LIKE = 12;
  int TK_IN = 13;
  int TK_IS = 14;
  int TK_ESCAPE = 15;
  int TK_MINUS = 16;
  int TK_PLUS = 17;
  int TK_MULT = 18;
  int TK_DIV = 19;
  int TK_EQ = 20;
  int TK_NE = 21;
  int TK_GT = 22;
  int TK_GE = 23;
  int TK_LT = 24;
  int TK_LE = 25;
  int TK_LPAREN = 26;
  int TK_RPAREN = 27;
  int TK_SEMICOLON = 28;
  int TK_COMMA = 29;
  int TK_LONG = 30;
  int TK_DOUBLE = 31;
  int TK_FLOAT = 32;
  int TK_STRING = 33;
  int TK_IDENTIFIER = 34;
  int TK_LETTER = 35;
  int TK_DIGIT = 36;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"NULL\"",
    "\"OR\"",
    "\"AND\"",
    "\"NOT\"",
    "\"BETWEEN\"",
    "\"LIKE\"",
    "\"IN\"",
    "\"IS\"",
    "\"ESCAPE\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "<TK_LONG>",
    "<TK_DOUBLE>",
    "<TK_FLOAT>",
    "<TK_STRING>",
    "<TK_IDENTIFIER>",
    "<TK_LETTER>",
    "<TK_DIGIT>",
  };

}
