package org.springframework.web.servlet.view.velocity;

import java.util.Locale;

import org.springframework.web.servlet.View;
import org.springframework.web.servlet.view.UrlBasedViewResolver;

/**
 * Convenience subclass of UrlBasedViewResolver that supports VelocityView
 * (i.e. Velocity templates) and custom subclasses of it.
 *
 * <p>The view class for all views generated by this resolver can be specified
 * via setViewClass. See UrlBasedViewResolver's javadocs for details.
 *
 * @author Juergen Hoeller
 * @since 13.12.2003
 * @see #setViewClass
 * @see #setPrefix
 * @see #setSuffix
 * @see #setRequestContextAttribute
 * @see #setDateToolAttribute
 * @see VelocityView
 */
public class VelocityViewResolver extends UrlBasedViewResolver {

	private String dateToolAttribute;

	/**
	 * Sets default viewClass to VelocityView.
	 * @see #setViewClass
	 */
	public VelocityViewResolver() {
		setViewClass(VelocityView.class);
	}

	/**
	 * Requires VelocityView.
	 * @see VelocityView
	 */
	protected Class requiredViewClass() {
		return VelocityView.class;
	}

	/**
	 * Set the name of the DateHool helper object to expose in the Velocity context
	 * of this view, or null if not needed. DateTool is from Velocity Tools.
	 */
	public void setDateToolAttribute(String dateToolAttribute) {
		this.dateToolAttribute = dateToolAttribute;
	}

	protected View loadView(String viewName, Locale locale) {
		VelocityView view = (VelocityView) super.loadView(viewName, locale);
		view.setDateToolAttribute(this.dateToolAttribute);
		return view;
	}

}
