package org.springframework.web.servlet.view;

/**
 * Convenience subclass of UrlBasedViewResolver that supports InternalResourceView
 * (i.e. Servlets and JSPs), and subclasses like JstlView and TilesView.
 *
 * <p>The view class for all views generated by this resolver can be specified
 * via setViewClass. See UrlBasedViewResolver's javadocs for details.
 *
 * <p>BTW, it's good practice to put JSP files that just serve as views under
 * WEB-INF, to hide them from direct access (e.g. via a manually entered URL).
 * Only controllers will be able to access them then.
 *
 * @author Juergen Hoeller
 * @since 17.02.2003
 * @see #setViewClass
 * @see #setPrefix
 * @see #setSuffix
 * @see #setRequestContextAttribute
 * @see InternalResourceView
 * @see JstlView
 * @see org.springframework.web.servlet.view.tiles.TilesView
 */
public class InternalResourceViewResolver extends UrlBasedViewResolver {

	/**
	 * Sets default viewClass to InternalResourceView.
	 * @see #setViewClass
	 */
	public InternalResourceViewResolver() {
		setViewClass(InternalResourceView.class);
	}

	/**
	 * Requires InternalResourceView.
	 * @see InternalResourceView
	 */
	protected Class requiredViewClass() {
		return InternalResourceView.class;
	}

}
